### Read data from income.csv and scale the relevant features using standardization

In [1]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [2]:
df = pd.read_csv('income.csv')

In [3]:
df.head()

      Name  Age  Income  Buy
0      Rob   27   70000  Yes
1  Michael   29   90000   No
2    Mohan   29   61000  Yes
3   Ismail   28   60000  Yes
4     Kory   42  150000   No

In [4]:
# numerical_features = ['Age','Income']

In [5]:
scaler = StandardScaler()

In [11]:
# df[numerical_features] = scaler.fit_transform(df[numerical_features])

In [8]:
df[['Age','Income']] = scaler.fit_transform(df[['Age','Income']])

In [9]:
df.head()

      Name       Age    Income  Buy
0      Rob -1.356055 -0.480684  Yes
1  Michael -1.009157 -0.010159   No
2    Mohan -1.009157 -0.692421  Yes
3   Ismail -1.182606 -0.715947  Yes
4     Kory  1.245679  1.401417   No